# Generated by Django 4.1.5 on 2024-01-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='comentario',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
