# Generated by Django 4.1.5 on 2024-01-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadocuenta',
            name='pagada',
        ),
        migrations.AddField(
            model_name='estadocuenta',
            name='estado',
            field=models.CharField(blank=True, choices=[('pagado', 'Pagado'), ('no_pagado', 'No Pagado')], default='no_pagado', max_length=10, null=True),
        ),
    ]
