# Generated by Django 4.1.5 on 2024-01-23 03:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_delete_transaccion'),
        ('inventario', '0005_alter_producto_existencia'),
        ('ventas', '0009_remove_detalleventa_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(db_column='producto', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.producto'),
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('abono', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_venta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_cliente', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cliente', models.ForeignKey(db_column='cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transacciones_venta', to='ventas.venta')),
            ],
            options={
                'db_table': 'Transaccion',
            },
        ),
    ]
