# Generated by Django 4.1.5 on 2024-01-23 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_producto_existencia'),
        ('ventas', '0010_detalleventa_producto_transaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(db_column='producto', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.producto'),
        ),
    ]
