# Generated by Django 4.1.5 on 2024-01-23 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_alter_detalleventa_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='producto',
            new_name='id_producto',
        ),
        migrations.RenameField(
            model_name='detalleventa',
            old_name='venta',
            new_name='id_venta',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='cliente',
            new_name='id_cliente',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='venta',
            new_name='id_venta',
        ),
    ]
