# Generated by Django 4.1.5 on 2024-01-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_rename_producto_detalleventa_id_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='ganancias',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
