# Generated by Django 4.1.5 on 2024-01-24 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_detalleventa_ganancias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='ganancias',
            new_name='ganancia',
        ),
    ]
