# Generated by Django 4.1.5 on 2024-03-14 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0015_venta_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='id_venta',
            field=models.ForeignKey(db_column='venta', on_delete=django.db.models.deletion.CASCADE, to='ventas.venta'),
        ),
    ]
