# Generated by Django 3.2.6 on 2023-12-30 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0004_rename_idprducto_producto_idproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idcompra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('costo_compra', models.FloatField()),
                ('cantidad', models.FloatField()),
                ('observaciones', models.CharField(max_length=200, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
            options={
                'unique_together': {('idcompra', 'producto')},
            },
        ),
    ]
