# Generated by Django 3.2.6 on 2023-12-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
