# Generated by Django 3.2.6 on 2023-12-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_compra_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='compra',
            name='costo_compra',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
