# Generated by Django 4.1.5 on 2024-01-22 05:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_saldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('abono', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_venta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_cliente', models.DecimalField(decimal_places=2, max_digits=15)),
                ('id_clientes', models.ForeignKey(db_column='id_clientes', on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente')),
            ],
            options={
                'db_table': 'Transaccion',
            },
        ),
    ]
