# Generated by Django 4.1.5 on 2024-01-23 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_transaccion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaccion',
        ),
    ]
