# Generated by Django 4.1.5 on 2024-01-28 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_ruta_activo'),
        ('clientes', '0005_delete_transaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ruta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rutas.ruta'),
        ),
    ]
