# Generated by Django 4.1.5 on 2024-01-29 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_ruta_activo'),
        ('clientes', '0006_cliente_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ruta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rutas.ruta'),
        ),
    ]
