# Generated by Django 4.1.5 on 2024-03-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_cliente_ruta'),
    ]

    operations = [
        migrations.CreateModel(
            name='saldoInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_inical', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estado', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'saldoInicial',
            },
        ),
    ]
