# Generated by Django 4.1.5 on 2024-03-14 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_saldoinicial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saldoinicial',
            old_name='saldo_inical',
            new_name='saldo_inicial',
        ),
        migrations.AddField(
            model_name='saldoinicial',
            name='cliente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
    ]
