# Generated by Django 4.1.5 on 2024-03-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_rename_saldo_inical_saldoinicial_saldo_inicial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldoinicial',
            name='abono_saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
