# Generated by Django 4.1.5 on 2024-03-15 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_saldoinicial_abono_saldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonoSaldoInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto_SI', models.DecimalField(decimal_places=2, max_digits=15)),
                ('id_saldo_inicial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.saldoinicial')),
            ],
            options={
                'db_table': 'abonosSaldoInicial',
            },
        ),
    ]
