# Generated by Django 4.1.5 on 2024-01-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ruta', models.CharField(max_length=50)),
                ('descripcion_ruta', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rutas',
            },
        ),
    ]
