# Generated by Django 4.1.5 on 2024-01-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='activo',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
