# Generated by Django 3.2.6 on 2023-12-29 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20231226_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='idprducto',
            new_name='idproducto',
        ),
    ]
